### ISSUE TITLE
There is an example how to interpolate two colors?

### ISSUE THREAD

**Issue by diegorodriguesvieira** [ajsmth/react-native-pager#27]

**Comment by ajsmth** [comment]
hey there - there isn't an example of this just yet as I doubt it's supported out of the box with the interpolate functions of this library. However you should be able to use the animatedIndex node and interpolate colors that way - a library like react-native-redash or the base react-native-reanimated have examples of how to do this: https://wcandillon.github.io/react-native-redash/colors
