### ISSUE TITLE
Swipe not working with React Native CLI Project for version 0.2.2 published on npm

### ISSUE THREAD

**Issue by balzdur** [ajsmth/react-native-pager#31]
**Expected Behavior**

I am trying to create a sample pager like the one depicted in the `README.md`.

**Actual Behavior**

The Swipe is not working. It is just stuck on the first Slide.
To rule out any issue with my current project (e.g. missconfiguration like in #22), the swipe work with `v0.2.1` published on npm.

**Environment**

React: 16.9.0
React native: 0.61.5
@crowdlinker/react-native-pager: 0.2.2
react-native-gesture-handler: 1.6.0
react-native-reanimated: 1.7.0

**Target Platform:**
iOS & Android

-------------
EDIT: It looks like the difference between `0.2.1` and `0.2.2` is linked to [this PR](https://github.com/ajsmth/react-native-pager/pull/13) which is not merged yet on this project (maybe you just publish on npm and forgot to push the merge on github?)

**Comment by ajsmth** [comment]
hey there - thanks for taking a look. If that is the case then its definitely a mistake, that PR breaks existing functionality so it'll need work before it should be released. I'll release a new version with that removed, in the mean time please revert to 0.2.1 - thanks!

**Comment by ajsmth** [comment]
`v0.2.3` is out - i suspect `0.2.2` was a mistake on my part

**Comment by balzdur** [comment]
Thanks for you're reactivity and nice work, the package is awesome !
