### ISSUE TITLE
How to use vertical infinite scrolling flatlist inside horizontal pager?

### ISSUE THREAD

**Issue by rasanu** [ajsmth/react-native-pager#33]
Not able to use both horizontal pager and children vertical scroll.

**Comment by rasanu** [comment]
Sort it out.. Thankx By the Way

**Comment by Doko-Demo-Doa** [comment]
How did you solve it?

**Comment by chrissloey** [comment]
If anyone else comes across this, nested vertical scrolling worked for me when I added the `type={'horizontal'}` prop to the `Pager`
