### ISSUE TITLE
Cannot set Initial Index

### ISSUE THREAD

**Issue by wzahedi** [ajsmth/react-native-pager#36]
Hello, I am using this library for a simple vertical slider, where the initial index needs to be set to 1. However, it renders at index 0 initially, until I start swiping or the page re-renders. I cannot seem to figure out why. It does not work horizontally, or even with PageProvider wrapping this. Here is an example of what I am doing, inside a functional component. Thanks.

```javascript
const [activeIndex, onChange] = useState(1);
  return (
    <Pager
      onChange={onChange}
      initialIndex={1}
      activeIndex={activeIndex}
      style={{ flex: 1 }}
      type='vertical'>
      <Animated.View style={{ backgroundColor: '#777', flex: 1 }/>
      <Animated.View style={{ backgroundColor: '#555', flex: 1 }}>
      <Animated.View style={{ backgroundColor: '#333', flex: 1 }}>
    </Pager>
  );
};
```

**Comment by ajsmth** [comment]
hey there - I've just tried this and wasn't able to replicate - can you provide more details about your environment / potential other elements that might be affecting this component? is it iOS or Android? thanks

**Comment by wzahedi** [comment]
Unfortunately I ended up implementing my use case a different way, I will close this issue now, thanks!
